### ISSUE TITLE
[Chapter 03] 작동 확인하는 코드 작성하기

### ISSUE THREAD

**Issue by dnwls16071** [shinsunyoung/springboot-developer-2rd#12]
안녕하세요.  @shinsunyoung 개발자님.

혼자서 공부했던 스프링 개념을 이 책을 통해 다시 복습하고 실제로 간단하게 서비스를 만들어보고자 책을 구매해서 시작하게 되었는데요.

계층별 구현 완료 후 작동을 확인하는 과정에서 책의 코드가 실행되지 않았고 공식문서를 찾아가며 5시간 정도 삽질한 결과 정상적으로 더미 데이터(`data.sql`)가 들어가고 DDL문이 정상적으로 실행되어 Member 테이블이 만들어지는 것을 확인해서 공유드리고자 이슈로 남기게 되었습니다.

인텔리제이로 작업을 할 때 DDL data source와 Data Source를 둘 다 설정해야 에러가 없이 정상적으로 동작하더군요...
또한 추가로 `application.yml` 코드 부분도 별도로 작성한 부분이 있어 이 부분을 공유해드리고자 이슈를 남기게 되었습니다.

`application.yml` 코드

```yml
spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
    show-sql: true

  datasource:
    url: jdbc:h2:tcp://localhost/~/springboot-developer
    driverClassName: org.h2.Driver
    username: sa
    password:

  # 추가로 작성한 부분
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      schema-locations: classpath:schema.sql
```

`data.sql` → 이건 책에 나온 것 써도 문제가 없었지만 한 번 많이 넣어보고싶어서 이렇게 작성하게 되었습니다.

```sql
INSERT INTO MEMBER (id, name) VALUES ( 1, 'name 1' );
INSERT INTO MEMBER (id, name) VALUES ( 2, 'name 2' );
INSERT INTO MEMBER (id, name) VALUES ( 3, 'name 3' );
INSERT INTO MEMBER (id, name) VALUES ( 4, 'name 4' );
INSERT INTO MEMBER (id, name) VALUES ( 5, 'name 5' );
INSERT INTO MEMBER (id, name) VALUES ( 6, 'name 6' );
INSERT INTO MEMBER (id, name) VALUES ( 7, 'name 7' );
INSERT INTO MEMBER (id, name) VALUES ( 8, 'name 8' );
INSERT INTO MEMBER (id, name) VALUES ( 9, 'name 9' );
INSERT INTO MEMBER (id, name) VALUES ( 10, 'name 10' );
```

`schema.sql`

```sql
DROP TABLE IF EXISTS MEMBER CASCADE;

CREATE TABLE MEMBER (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);
```

타 강좌에서 공부했을 때 DDL문은 별도로 관리해주는 것이 좋다고 배워 `resources` 폴더 하위에 DDL문과 더미 데이터를 같이 보관하였습니다.
어렵사리 해결은 했지만 이렇게 해결하는 것이 올바른 방법인지 여쭙고 싶습니다.

![image](https://github.com/shinsunyoung/springboot-developer-2rd/assets/106802375/8401e9fd-e353-4790-a207-2d9e21b7fc45)
