### ISSUE TITLE
[Chapter6] 블로그 기획하고 API 만들기, 189p 실행 테스트 하기 01단계 관련하여 

### ISSUE THREAD

**Issue by yeongjuleee** [shinsunyoung/springboot-developer-2rd#24]
테스트를 쉽게 하기 위해 data.sql 파일을 생성 후 실행을 할 때 일어난 문제입니다. 
```
INSERT INTO article(title, content) VALUES ('제목1', '내용1');
INSERT INTO article(title, content) VALUES('제목2', '내용2');
```
해당 부분에서 제가 사용하는 인텔리제이에서는 Database source를 연결하라고 나와 application.yml에 입력해둔 url과  포스트맨에서 사용하는 localhost 번호를 보고 연결을 했습니다만, 자꾸 article 테이블이 존재하지 않는다는 오류를 겪었습니다.  

그래서 application.yml 파일을 열어 작가님께서 설정한 내용으로 교체해보았지만 계속해서 article 테이블이 존재하지 않는다는 오류가 발생하였고, 아래와 같은 방법으로 해결을 했습니다. 

변경한 application.yml
```
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: false
    ## defer-datasource-initialization : 즉시 데이터 소스 초기화 설정 (true : 지연 / false : 즉시 초기화 설정)
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
## H2 콘솔 활성화
  h2:
    console:
      enabled: true
```

src/resoucres 에서 schema.sql을 생성하여 실행
```
CREATE TABLE IF NOT EXISTS article(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content VARCHAR(255) NOT NULL
);
```
이후 data.sql 파일 생성 및 실행
```
INSERT INTO article (title, content) values ('제목 1', '내용 1');
INSERT INTO article (title, content) values ('제목 2', '내용 2');
INSERT INTO article (title, content) values ('제목 3', '내용 3')
```

이렇게 하였더니 값이 잘 전달되었고, 포스트맨에서 GET으로 HTTP 메서드를 변경하고 url을 책에 나온 것 같이 했더니 결과값이 잘 나왔습니다.
