### ISSUE TITLE
[챕터3] defer-datasource-initialization: true 를 통한 data.sql 작동 안하는 문제

### ISSUE THREAD

**Issue by aectarine** [shinsunyoung/springboot-developer-2rd#51]
```
spring:
  application:
    name: Springboot-Developer
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/study_spring_book
    username: study
    password: "0000"
  jpa:
    # 전송 쿼리 확인
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    # 테이블 생성 후 import.sql 실행
    defer-datasource-initialization: true
```
위의 설정인 경우, resources/data.sql -> import.sql로 변경 후 INSERT 동작 확인
